import { createServer, type Socket } from 'node:net';
import { join } from 'node:path';
import { Effect } from 'effect';
import type { IPty } from 'node-pty';
import { type DaemonEvent, type DaemonRequest, decodeRequest, encodeFrame, PROTOCOL_VERSION } from './protocol';
import { createPty, resizePty, terminatePty, writePty } from './pty';
import { makeRegistry, type RunRecord, type ServiceRecord } from './registry';

type Subscriber = (event: { data: string; offset: number }) => void;
type LiveService = { terminal: IPty; leaseId: string | undefined };
export type Daemon = { listen: () => Promise<void>; close: () => Promise<void>; request: (request: DaemonRequest) => Promise<unknown>; subscribe: (runId: string, serviceName: string, subscriber: Subscriber) => () => void };
const serviceKey = (runId: string, serviceName: string) => `${runId}:${serviceName}`;
const parseShellCommand = (command: string) => ['/bin/sh', ['-c', command]] as const;

/** Owns live PTYs and durable run state. Unix socket framing is kept at the edge. */
export const makeDaemon = (options: { socketPath: string; dataDirectory: string }): Daemon => {
	const registry = makeRegistry(options.dataDirectory);
	const subscribers = new Map<string, Set<Subscriber>>();
	const terminals = new Map<string, LiveService>();
	const server = createServer((socket) => serveSocket(socket));
	const publish = (runId: string, serviceName: string, event: { data: string; offset: number }) => { const readers = subscribers.get(serviceKey(runId, serviceName)); if (readers !== undefined) for (const reader of readers) queueMicrotask(() => reader(event)); };
	const findService = async (runId: string, serviceName: string) => { const runs = await registry.list(); const run = runs.find((candidate) => candidate.runId === runId); const service = run?.services.find((candidate) => candidate.name === serviceName); if (run === undefined || service === undefined) throw new Error(`Service ${serviceName} in run ${runId} was not found`); return { run, service }; };
	const stopRun = async (runId: string) => { const run = await registry.update(runId, (current) => ({ ...current, state: 'stopping' })); await Promise.all(run.services.map(async (service) => { const live = terminals.get(serviceKey(run.runId, service.name)); if (live !== undefined) { await Effect.runPromise(terminatePty(live.terminal, service.command)); terminals.delete(serviceKey(run.runId, service.name)); } })); return registry.update(runId, (current) => ({ ...current, state: 'exited', services: current.services.map((service) => ({ ...service, state: service.state === 'stopping' || service.state === 'running' ? 'exited' as const : service.state })) })); };
	const startRun = async (request: Extract<DaemonRequest, { method: 'startRun' }>) => {
		const services: Array<ServiceRecord> = request.params.services.map((service) => ({ name: service.name, command: service.command, cwd: service.cwd, pid: 0, logPath: join(options.dataDirectory, 'logs', request.params.runId, `${service.name}.log`), state: 'starting' }));
		const run: RunRecord = { runId: request.params.runId, projectName: request.params.projectName, presetName: request.params.presetName, invocationCwd: request.params.invocationCwd, configSnapshot: request.params.configSnapshot, startedAt: new Date().toISOString(), state: 'starting', services };
		await registry.reserve(run);
		try { for (const service of run.services) { const shell = parseShellCommand(service.command); const terminal = await Effect.runPromise(createPty({ command: shell[0], args: [...shell[1]], cwd: service.cwd, env: request.params.environment, cols: 80, rows: 24 })); const key = serviceKey(run.runId, service.name); const live: LiveService = { terminal, leaseId: undefined }; service.pid = terminal.pid; service.state = 'running'; terminals.set(key, live); terminal.onData((data) => { void registry.appendLog(service, data).then((offset) => publish(run.runId, service.name, { data, offset })); }); terminal.onExit((event) => { terminals.delete(key); service.state = event.exitCode === 0 ? 'exited' : 'failed'; void registry.update(run.runId, (stored) => ({ ...stored, state: service.state, services: stored.services.map((storedService) => storedService.name === service.name ? service : storedService) })); }); } return registry.update(run.runId, () => ({ ...run, state: 'running' })); }
		catch (cause) { await Promise.all(run.services.map(async (service) => { const live = terminals.get(serviceKey(run.runId, service.name)); if (live !== undefined) await Effect.runPromise(terminatePty(live.terminal, service.command).pipe(Effect.catch(() => Effect.void))); })); await registry.update(run.runId, (current) => ({ ...current, state: 'failed', services: current.services.map((service) => ({ ...service, state: service.state === 'running' || service.state === 'starting' ? 'failed' as const : service.state })) })); throw cause; }
	};
	const request = async (incoming: DaemonRequest): Promise<unknown> => {
		if (incoming.method === 'listRuns') return registry.list(); if (incoming.method === 'startRun') return startRun(incoming); if (incoming.method === 'stopRun') return stopRun(incoming.params.runId);
		const found = await findService(incoming.params.runId, incoming.params.serviceName); if (incoming.method === 'tail') return registry.readLog(found.service, incoming.params.after ?? 0); const live = terminals.get(serviceKey(found.run.runId, found.service.name));
		if (incoming.method === 'attach') { if (live === undefined) throw new Error('Service is not live'); if (live.leaseId !== undefined) throw new Error('Service already has an input writer'); live.leaseId = crypto.randomUUID(); return { leaseId: live.leaseId }; }
		if (live === undefined || live.leaseId !== incoming.params.leaseId) throw new Error('Input writer lease is not held'); if (incoming.method === 'input') { await Effect.runPromise(writePty(live.terminal, incoming.params.data)); return {}; } await Effect.runPromise(resizePty(live.terminal, incoming.params.cols, incoming.params.rows)); return {};
	};
	const subscribe = (runId: string, serviceName: string, subscriber: Subscriber) => { const key = serviceKey(runId, serviceName); const readers = subscribers.get(key) ?? new Set<Subscriber>(); readers.add(subscriber); subscribers.set(key, readers); return () => { readers.delete(subscriber); if (readers.size === 0) subscribers.delete(key); }; };
	const write = (socket: Socket, frame: Parameters<typeof encodeFrame>[0]) => { void Effect.runPromise(encodeFrame(frame)).then((data) => socket.write(`${data}\n`)); };
	const serveSocket = (socket: Socket) => { let input = ''; const cleanups = new Set<() => void>(); const cleanup = () => { for (const unsubscribe of cleanups) unsubscribe(); cleanups.clear(); }; socket.once('close', cleanup); socket.once('error', cleanup); socket.on('data', (chunk) => { input += chunk.toString(); const lines = input.split('\n'); input = lines.pop() ?? ''; for (const line of lines) { if (line.length === 0) continue; void Effect.runPromise(decodeRequest(line)).then(async (incoming) => { try { if (incoming.method === 'tail' || incoming.method === 'attach') { const found = await findService(incoming.params.runId, incoming.params.serviceName); const replay = await registry.readLog(found.service, incoming.method === 'tail' ? incoming.params.after ?? 0 : 0); if (replay.data.length > 0) write(socket, { version: PROTOCOL_VERSION, requestId: incoming.requestId, event: 'output', data: replay.data, offset: replay.offset } satisfies DaemonEvent); cleanups.add(subscribe(incoming.params.runId, incoming.params.serviceName, (event) => write(socket, { version: PROTOCOL_VERSION, requestId: incoming.requestId, event: 'output', data: event.data, offset: event.offset }))); } const result = await request(incoming); write(socket, { version: PROTOCOL_VERSION, requestId: incoming.requestId, ok: true, result }); } catch (cause) { write(socket, { version: PROTOCOL_VERSION, requestId: incoming.requestId, ok: false, error: cause instanceof Error ? cause.message : String(cause) }); } }, (cause) => write(socket, { version: PROTOCOL_VERSION, requestId: 'invalid', ok: false, error: String(cause) })); } }); };
	return { listen: () => new Promise((resolve, reject) => { server.once('error', reject); server.listen(options.socketPath, () => { server.off('error', reject); resolve(); }); }), close: async () => { await Promise.all([...terminals.values()].map((live) => Effect.runPromise(terminatePty(live.terminal, 'daemon shutdown').pipe(Effect.catch(() => Effect.void))))); await new Promise<void>((resolve, reject) => server.close((error) => error === undefined ? resolve() : reject(error))); }, request, subscribe };
};
