export const TERMINATION_POLL_INTERVAL_MS = 25;
export const TERMINATION_POLL_ATTEMPTS = 200;
export const TERMINATION_PHASE_TIMEOUT_MS =
	TERMINATION_POLL_INTERVAL_MS * TERMINATION_POLL_ATTEMPTS;
export const STOP_REQUEST_MARGIN_MS = 1_000;
export const STOP_REQUEST_TIMEOUT_MS =
	TERMINATION_PHASE_TIMEOUT_MS * 2 + STOP_REQUEST_MARGIN_MS;
export const DEFAULT_DAEMON_REQUEST_TIMEOUT_MS = 5_000;

export const PROCESS_INSPECTION_TIMEOUT_MS = 500;
export const GROUP_LIVENESS_BACKOFF_INITIAL_MS = 25;
export const GROUP_LIVENESS_BACKOFF_MAX_MS = 250;

export const TERMINATION_TERM_SIGNAL = 15;
export const TERMINATION_KILL_SIGNAL = 9;
